package scraper;

import java.awt.Image;

public class Card {
	
	String name;
	String type;
	String faction;
	String loyalty;
	int power;
	String rarity;
	String lane;
	String scrapCost;
	String scrapCostPremium;
	String millCost;
	String millCostPremium;
	Image picture;
	String cardText;
	String flavorText;
	
	// Autogenerated constructor
	public Card(String name, String type, String faction, String loyalty, int power, String rarity, String lane,
			String scrapCost, String scrapCostPremium, String millCost, String millCostPremium, Image picture,
			String cardText, String flavorText) {
		
		
		this.name = name;
		this.type = type;
		this.faction = faction;
		this.loyalty = loyalty;
		this.power = power;
		this.rarity = rarity;
		this.lane = lane;
		this.scrapCost = scrapCost;
		this.scrapCostPremium = scrapCostPremium;
		this.millCost = millCost;
		this.millCostPremium = millCostPremium;
		this.picture = picture;
		this.cardText = cardText;
		this.flavorText = flavorText;
	}
	

	
	
	

	
	
	
}
